### ISSUE TITLE
Bouquets reference

### ISSUE THREAD

**Issue by wasiaks** [grzegorz914/homebridge-openwebif-tv#1]
Hi, where can I find bouquets reference - to complete config?

**Comment by grzegorz914** [comment]
Hi,
here:
http://IP of Your receiver/api/getallservices
or after restart homebridge complete JSON channels Configuration in log.

**Comment by wasiaks** [comment]
Hi, thank you for your answer, but I think, I’m doing something wrong :-(

I’ve got this:

**Comment by grzegorz914** [comment]
Check this:
http://ip/api/about

looks like Your sat receiver uses old openwebif with web XML instead api.
Please update your openwebif in your sat receiver, disable http authentication.

**Comment by wasiaks** [comment]
Grzegorz - thank you!
I've made an update - now it works fine :-)

Do you think is there any chance to add volume control?

**Comment by grzegorz914** [comment]
Volume control is integrated in the app but right now HomeKit app does not support volume control from inside TV accessory.

**Comment by grzegorz914** [comment]
Due to bouquets, if U have not more as 100 channels in all bouquets, no need to ad them to the config manually.
Last update download all channels from receiver itself if bouquets in config is empty. If U want to test this please remove all channels from config and restart Homebridge.
