### ISSUE TITLE
2.1.15 Warning during installation

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#14]
Hi,
during installation of 2.1.15

`sudo npm -g install homebridge-openwebif-tv
`
I got following warning:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
+ homebridge-openwebif-tv@2.1.15
updated 1 package in 1.701s
```

Can you please have a look or give advise?
regards
Birnbam

**Comment by grzegorz914** [comment]
This warning is from npm, more here: https://www.npmjs.com/package/request
