### ISSUE TITLE
2.1.27 "No response" when playing IPTV or mp3 streams

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#15]
Hi,

When playing tv the app reports the running service e.g. "PULS 4 Austria
config sniplet:
`{ "name": "PULS 4 Austria", "reference": "1:0:1:4E27:43A:1:C00000:0:0:0:" }`

but when I'm running a mp3 radio the app reports "No response"
config sniplet:
`{ "name": "Radio Regenbogen", "reference": "4097:0:1:0:0:0:0:0:0:0:http%3A//streams.regenbogen.de/rr-kinderlieder-128-mp3" }`

Can you please have a look?

Best regards
birnbam

**Comment by grzegorz914** [comment]
Hi,

I tested Your config and working without any problems.
