### ISSUE TITLE
Exposing Speaker accessories to HomeKit

### ISSUE THREAD

**Issue by fnolting** [grzegorz914/homebridge-openwebif-tv#18]
In an earlier version, the speaker accessories were exposed to HomeKit as well so I could control the volume of my TVs via HomeKit but now I only see them in the Homebridge GUI and they aren't exposed to HomeKit anymore.

**Comment by grzegorz914** [comment]
U can control Volume using Volume buttons on iPhone or iPad. Just go to RC control and press hardware volume buttons.
