### ISSUE TITLE
Doesn't show up on homekit

### ISSUE THREAD

**Issue by hugohuetor** [grzegorz914/homebridge-openwebif-tv#19]
When installing openwebif on homebridge, I can not add it to homekit, the ascesorio does not appear in homekit, I try manually but can not find it and I can not enter code, 2 days ago I was going well, delete the ascesorio for tests and since then I can not connect it

**Comment by grzegorz914** [comment]
Change the Name of this accessory in config and try again or remove cache in Homebridge.

**Comment by hugohuetor** [comment]
thanks, solved
