### ISSUE TITLE
VU+ Uno 4K shown as "not responding" in HomeKit

### ISSUE THREAD

**Issue by fnolting** [grzegorz914/homebridge-openwebif-tv#22]
I can remote control my "VU+ Uno 4K" via the Homebridge UI just fine but it shows up as "not responding" in HomeKit. I found out that HomeKit doesn't like speial characters in accessory names so I deleted the + in the name but that didn't help. That already worked a few versions before so maybe something went wrong in one of the last releases. Please let me know if I can provide logs or anything else.

**Comment by grzegorz914** [comment]
Try to remove the tile from HomeKit app, change the name in config.json, restart homebridge and add it again to HimeKit app.

**Comment by fnolting** [comment]
That worked - thanks!
