### ISSUE TITLE
2.4.7 beta 1 ordering favorites

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#23]
Hi,
each time I restart homebridge, the openwebif-tv icon in my favorites is rearranged to the end (last icon).
This is odd because this was working in older versions.

Any ideas?

Best regards
birnbam

**Comment by grzegorz914** [comment]
Please update and test.

**Comment by birnbam** [comment]
Seems to be solved. Thank you!
