### ISSUE TITLE
No TV Settings

### ISSUE THREAD

**Issue by cgorms** [grzegorz914/homebridge-openwebif-tv#24]
Hi

Device added into HomeKit all though I'm not able to view TV Settings i.e Volume controls etc?

Any assistance would be appreciated...

**Comment by grzegorz914** [comment]
Which one of TV model U use?
Any log?
After add this to the HomeKit app in normal case is present as TV service,
![Zrzut ekranu 2020-04-12 o 18 17 54](https://user-images.githubusercontent.com/28867813/79073974-f05be580-7ce9-11ea-92a1-8e86210afc68.png)
after long press U get more options:
![Zrzut ekranu 2020-04-12 o 18 19 01](https://user-images.githubusercontent.com/28867813/79073993-184b4900-7cea-11ea-894f-e721f2380cb1.png)

**Comment by cgorms** [comment]
Presents as TV service but unable to turn volume up/down, mute or play/pause playback

![5D4E6A95-36F7-4D4E-8778-8640C995DBCF](https://user-images.githubusercontent.com/11981090/79075216-63b12780-7ce9-11ea-9af9-b511ecb64118.png)

When I add bouquets they appear as additional services...

**Comment by cgorms** [comment]
Log file...

[Homebridge] [4/12/2020, 5:47:34 PM] [IPTV_1] is running on port 42401.
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Device: 192.168.1.201, name: IPTV_1, state: Online
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] -------- IPTV_1 --------
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Manufacturer: Vu+
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Model: undefined
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Kernel: 3.13.5
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Chipset: 7356
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Webif version.: OWIF 1.3.9
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] Firmware: 2020-04-08
[Homebridge] [4/12/2020, 5:47:38 PM] [OpenWebIfTv] ----------------------------------
[Homebridge] [4/12/2020, 5:47:44 PM] [OpenWebIfTv] Device: 192.168.1.201, get current Power state successfull: ON
[Homebridge] [4/12/2020, 5:47:52 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 358
[Homebridge] [4/12/2020, 5:47:52 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 174
[Homebridge] [4/12/2020, 5:47:52 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 358
[Homebridge] [4/12/2020, 5:47:53 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 174
[Homebridge] [4/12/2020, 5:47:54 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 358
[Homebridge] [4/12/2020, 5:47:56 PM] [OpenWebIfTv] Device: 192.168.1.201, setPowerModeSelection successfull, state: SHOW, command: 174
[Homebridge] [4/12/2020, 5:49:28 PM] [OpenWebIfTv] Device: 192.168.1.201, get current Power state successfull: ON
[Homebridge] [4/12/2020, 6:10:45 PM] [OpenWebIfTv] Device: 192.168.1.201, get current Power state successfull: ON
[Homebridge] [4/12/2020, 6:11:59 PM] [OpenWebIfTv] Device: 192.168.1.201, get current Power state successfull: ON

**Comment by cgorms** [comment]
{
        "name": "IPTV_1",
        "host": "192.168.1.201",
        "port": 80,
        "auth": false,
        "user": "user",
        "pass": "pass",
        "switchInfoMenu": false
    }

**Comment by grzegorz914** [comment]
U need define also bouquets in config.json,
Volume/Mute and RC control is possible from RC control app on iPhone or iPad.

**Comment by cgorms** [comment]
My Bouquets are IPTV, how are these added?

**Comment by grzegorz914** [comment]
Check stored channels in homebridge_directory/openwebifTv/channels_1921681201,
U can copy this to Your bouquets config.

**Comment by cgorms** [comment]
Within openwebifTv/channels_1921681201 all are showing as...

  {
    "name": " ",
    "reference": "1:320:0:0:0:0:0:0:0:0:: "
  },
  {
    "name": " ",
    "reference": "1:320:0:0:0:0:0:0:0:0:: "
  }

**Comment by grzegorz914** [comment]
IPTV need to be just like this:

`{
                            "name": "Cam1",
                            "reference": "4097:0:0:0:0:0:0:0:0:0:rtsp%3a//homekit%3apdp-lx5090h@192.168.1.15%3a554/cam/mpeg4"
                        } `

U can look in to Your Bouquets on Your Sat Receiver and copy to the config.json, all reference can be found under channel info.

**Comment by grzegorz914** [comment]
U can also put this in web browser to get al services:

http://192.168.1.201/api/getallservices

**Comment by cgorms** [comment]
@grzegorz914 I'm appreciating you help.

This is my service reference....
"servicereference": "4097:0:1:29A:18C:0:0:0:0:0:http%3a//......./live/<logindetails>/396.ts:UK SKY CINEMA SCI FI & HORROR FHD"

I put the into the config.json 
                "bouquets": [
                        {
                            "name": "SKY CINEMA SCI FI & HORROR FHD",
                            "reference": "4097:0:1:29A:18C:0:0:0:0:0:http%3a//......./live/<logindetails>/396.ts:UK SKY CINEMA SCI FI & HORROR FHD"
                        },
 and when I delete it... it takes me to the radio epg??

**Comment by cgorms** [comment]
Also how can I pause/play movies??

**Comment by grzegorz914** [comment]
> Also how can I pause/play movies??

Go to RC control app on iPhone select your sat receiver from the top list and control your receiver:

![EC88E6E4-A167-4C79-B1B8-6972BA509F5D](https://user-images.githubusercontent.com/28867813/79077348-3bcdbe00-7d01-11ea-873e-0432738b2149.png)

**Comment by grzegorz914** [comment]
> :UK SKY CINEMA SCI FI & HORROR FHD

Remove this from reference:
`:UK SKY CINEMA SCI FI & HORROR FHD `

**Comment by cgorms** [comment]
> > Also how can I pause/play movies??
> 
> Go to RC control app on iPhone select your sat receiver from the top list and control your receiver:
> 
> ![EC88E6E4-A167-4C79-B1B8-6972BA509F5D](https://user-images.githubusercontent.com/28867813/79077348-3bcdbe00-7d01-11ea-873e-0432738b2149.png)

Can Siri reference this for pausing etc??

**Comment by grzegorz914** [comment]
I don’t know, just try to test this.

**Comment by cgorms** [comment]
> > :UK SKY CINEMA SCI FI & HORROR FHD
> 
> Remove this from reference:
> `:UK SKY CINEMA SCI FI & HORROR FHD`

Removed this... removed re-added Device select SKY CINEMA SCI FI & HORROR FHD from input and it goes quiet select epg to see source and its changed to radio not tv...

**Comment by grzegorz914** [comment]
Please Go to homebridge log and switch Your Sat Receiver using RC control from  Sat Receiver to this channel and look what reference will show in homebridge log, this reference can be added to config.json, in other case if U can get me the complete reference then I can test it on my receiver.
