### ISSUE TITLE
Inputs and IPTV

### ISSUE THREAD

**Issue by cgorms** [grzegorz914/homebridge-openwebif-tv#26]
![](https://user-images.githubusercontent.com/28867813/79073993-184b4900-7cea-11ea-894f-e721f2380cb1.png)

You posted this image with different Inputs how is this possible?

Also how can I zap an IPTV Channel? Currently this goes to the radio input on a Vu Solo2 running Pure2 image

**Comment by grzegorz914** [comment]
Get me one of Your reference, then I can test this.

**Comment by cgorms** [comment]
I will email details over later...

With regards the INPUTS i.e. Internet, VOD plugin etc how is this achieved?

**Comment by cgorms** [comment]
Using http://<IP Address>/api/about at the bottom it showed the service ref information which worked

**Comment by grzegorz914** [comment]
Nice
