### ISSUE TITLE
Add additional services - Netflix etc

### ISSUE THREAD

**Issue by cgorms** [grzegorz914/homebridge-openwebif-tv#27]
![](https://user-images.githubusercontent.com/28867813/79073993-184b4900-7cea-11ea-894f-e721f2380cb1.png)

How can I reference Netflix or a specific plugin OLM-FNC, as shown in the picture above?

**Comment by grzegorz914** [comment]
Sorry but this is not possible, openWebIf interface doesn’t contain this in its api.

**Comment by cgorms** [comment]
What about if you assign a plugin to a coloured button i.e. blue can that be called as a reference?

http://<IP address>/web/remotecontrol?command=401

**Comment by grzegorz914** [comment]
I will look on this possibility.

**Comment by cgorms** [comment]
That would be great - thank you

**Comment by grzegorz914** [comment]
Right now this not be added.
