### ISSUE TITLE
Channel list order

### ISSUE THREAD

**Issue by wasiaks** [grzegorz914/homebridge-openwebif-tv#3]
Hi Grzegorz - is it possible to change the order of channels in Home App?

I've added all the channels just as I've got them in bouquet, but in Home App they are in alphabetical order. 

BTW - great work with this plugin!

**Comment by grzegorz914** [comment]
U can just add number to every channel “neme” in config on first place or direct in the HomeKit app, then will be order as U want:

```
{“name”: “1 RTL”
“reference” “.....”
},
{
“name”: “2 ARD”,
“reference”: “.....”
}
```
