### ISSUE TITLE
Whats wrong with my configuration

### ISSUE THREAD

**Issue by MasterofKungfu9999** [grzegorz914/homebridge-openwebif-tv#30]
I'm using Hoobs and this is my configuration:

{
    "name": "Vu+",
    "host": "192.168.13.40",
    "port": 80,
    "auth": false,
    "user": "user",
    "pass": "pass",
    "volumeControl": true,
    "switchInfoMenu": true,
    "bouquets": [
        {
            "name": "Das Erste HD",
            "reference": "1:0:19:283D:3FB:1:C00000:0:0:0:"
        }
    ]
}

But i can't see anything in Homekit. 
Also i can't find a file named "channels_19216804"

What's wrong with my configuration?

**Comment by grzegorz914** [comment]
Look here for sample: 
https://github.com/grzegorz914/homebridge-openwebif-tv/blob/master/sample-config.json

**Comment by MasterofKungfu9999** [comment]
Now i get this error:

[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Device: 192.168.13.40, name: Vu+, state: Online[Homebridge] [4/28/2020, 19:14:36] ReferenceError: arrayLength is not defined
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-openwebif-tv/index.js:613:25)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)[Homebridge] [4/28/2020, 19:14:36] Got SIGTERM, shutting down Homebridge...[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] -------- Vu+ --------[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Manufacturer: Vu+[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Model: undefined[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Kernel: 3.14.28[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Chipset: 7252s[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Webif version.: OWIF 1.2.8[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] Firmware: 2020-02-25-vti-master (216bc5d2a)[Homebridge] [4/28/2020, 19:14:36] [OpenWebIfTv] ----------------------------------

**Comment by grzegorz914** [comment]
Please post Your complete config

**Comment by MasterofKungfu9999** [comment]
"server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYHHK5",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": xxxxxxxxx,
        "pin": "xxxxxxxxx",
        "username": "xxxxxxxxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "BlinkSecurityPlatform",
            "name": "Blink System",
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxxxxxx",
            "discovery": false,
            "plugin_map": {
                "plugin_name": "homebridge-blinkcameras"
            }
        },
        {
            "platform": "WeatherPlus",
            "service": "darksky",
            "key": "xxxxxxxxxx",
            "locationGeo": [
                xxxxxxxxx,
                xxxxxxxxx
            ],
            "interval": 4,
            "conditionCategory": "detailed",
            "forecast": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7
            ],
            "language": "de",
            "nameNow": "xxxxxxx",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "si"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": false,
            "users": {
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            },
            "lights": true,
            "wallSwitch": true,
            "heartrate": 2,
            "anyOn": true,
            "hosts": "192.168.13.48",
            "forceHttp": true
        },
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!Box 7590": {
                    "active": true,
                    "host": "192.168.13.1",
                    "port": 49000,
                    "username": "admin",
                    "password": "xxxxxxxxx",
                    "type": "dsl",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            true,
                            false
                        ],
                        "deflection": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ-Repeater": {
                    "active": true,
                    "host": "192.168.13.23",
                    "port": 49000,
                    "username": "admin",
                    "password": "xxxxxxxxxxxxx",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Repeater oben": {
                    "active": true,
                    "host": "192.168.13.25",
                    "port": 49000,
                    "username": "admin",
                    "password": "xxxxxxxxxxx",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Repeater 2400": {
                    "active": true,
                    "host": "192.168.13.54",
                    "port": 49000,
                    "username": "admin",
                    "password": "xxxxxxxxx",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                }
            },
            "callmonitor": {
                "active": false,
                "ip": "0.0.0.0",
                "port": 1012
            },
            "presence": {
                "user": [
                    {
                        "active": true,
                        "name": "Ronald",
                        "address": "192.168.13.39"
                    }
                ],
                "anyone": true,
                "offDelay": 10,
                "onDelay": 10,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "phoneBook": {
                "active": false
            },
            "alarm": {
                "active": false,
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": false,
                "measureTime": 5
            },
            "extReboot": {
                "active": false
            },
            "telegram": {
                "active": false
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": true,
            "disableAutoConfig": true,
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            }
        },
        {
            "platform": "DenonAVR",
            "plugin_map": {
                "plugin_name": "homebridge-denon-heos"
            },
            "pollInterval": 3,
            "debugToInfo": false,
            "devices": [
                {
                    "name": "Marantz Receiver",
                    "ip": "192.168.13.34",
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "VU+",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "SPOTIFY",
                            "name": "Spotify",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "BD",
                            "name": "Blu-Ray",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "TV",
                            "name": "TV"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "AVR on Apple TV",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "MPLAY",
                    "pollAllInput": false
                },
                {
                    "name": "AVR on VU+",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "SAT/CBL",
                    "defaultVolume": 45,
                    "pollAllInput": false
                },
                {
                    "name": "AVR on BlueRay",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "BD",
                    "defaultVolume": 45,
                    "pollAllInput": false
                }
            ],
            "volumeControl": [
                {
                    "name": "Receiver Volume",
                    "ip": "192.168.13.43",
                    "volumeLimit": 60,
                    "port": 8080
                }
            ]
        },
        {
            "platform": "OpenWebIfTv",
            "plugin_map": {
                "plugin_name": "homebridge-openwebif-tv"
            },
            "devices": [
                {
                    "name": "Vu+",
                    "host": "192.168.13.40",
                    "port": 80,
                    "auth": false,
                    "user": "user",
                    "pass": "pass",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "bouquets": [
                        {
                            "name": "Das Erste HD",
                            "reference": "1:0:19:283D:3FB:1:C00000:0:0:0:"
                        },
                        {
                            "name": "ZDF HD",
                            "reference": "1:0:19:2B66:3F3:1:C00000:0:0:0:"
                        },
                        {
                            "name": "RTL HD",
                            "reference": "1:0:19:EF10:421:1:C00000:0:0:0:"
                        },
                        {
                            "name": "SAT.1 HD",
                            "reference": "1:0:19:EF74:3F9:1:C00000:0:0:0:"
                        },
                        {
                            "name": "ProSieben HD",
                            "reference": "1:0:19:EF75:3F9:1:C00000:0:0:0:"
                        },
                        {
                            "name": "RTLII HD",
                            "reference": "1:0:19:EF15:421:1:C00000:0:0:0:"
                        },
                        {
                            "name": "VOX HD",
                            "reference": "1:0:19:EF11:421:1:C00000:0:0:0:"
                        },
                        {
                            "name": "kabel eins HD",
                            "reference": "1:0:19:EF76:3F9:1:C00000:0:0:0:"
                        },
                        {
                            "name": "SIXX HD",
                            "reference": "1:0:19:EF77:3F9:1:C00000:0:0:0:"
                        },
                        {
                            "name": "SUPER RTL HD",
                            "reference": "1:0:19:2E9B:411:1:C00000:0:0:0:"
                        },
                        {
                            "name": "TELE 5 HD",
                            "reference": "1:0:19:1519:455:1:C00000:0:0:0:"
                        },
                        {
                            "name": "ORF1 HD",
                            "reference": "1:0:19:132F:3EF:1:C00000:0:0:0:"
                        },
                        {
                            "name": "ORF2W HD",
                            "reference": "1:0:19:1330:3EF:1:C00000:0:0:0:"
                        },
                        {
                            "name": "RTL UHD",
                            "reference": "1:0:1F:307A:3F5:1:C00000:0:0:0:"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by grzegorz914** [comment]
Looks all ok, this is specific issue only with hobs, I will check this today leather.

**Comment by MasterofKungfu9999** [comment]
I think it's something with the bouquets

**Comment by grzegorz914** [comment]
Check 2.6.12, I think is fixed now

**Comment by MasterofKungfu9999** [comment]
I can see only 2.6.7 in Hoobs

**Comment by grzegorz914** [comment]
Check again 2.6.12 is online.

**Comment by MasterofKungfu9999** [comment]
Now it works. Thanks for your support!
