### ISSUE TITLE
configured channels not appearing

### ISSUE THREAD

**Issue by zobe123** [grzegorz914/homebridge-openwebif-tv#38]
in Wiki i found this information:
All reference and name from Your sat receiver are stored in homebridge_directory/openwebifTv/channels_19216804, if U want somthing changed in channel list please add Yours prefered channels to the config bouquets.

if i leave the config empty it shows "no channles configured"
can you do a fallback to the channels-File if no channel are in config-File?

**Comment by grzegorz914** [comment]
This is possible but many of people have more as 100 channels in its bouquets and in this case the app will no response due HomeKit limitation. It is simple to copy from the file channels in the config.json.

**Comment by zobe123** [comment]
ok, i haven't figured out if i have to copy it by hand.
why not just use the first 100 elements of Json? or only one defined bouquets,

**Comment by grzegorz914** [comment]
so, one bouquets can be more as 100 channels, use first 100 elements is not problem but how to know which channels U or other one People want to have on the lis?.
