### ISSUE TITLE
no connection to Dreambox 920

### ISSUE THREAD

**Issue by ekke1** [grzegorz914/homebridge-openwebif-tv#46]
After installing the plugin with Homebridge UI I'm getting the error below in the homebridge log.

If I use the same address with Safari (192.168.2.148:80) I'm getting on the dreambox 920 w/o any problem. 
Homebridge v.1.3.3; node v14.16.0; npm v7.6.0

Is there anything what I can do to resolve this issue?

devices": [
                {
                    "name": "dm920",
                    "host": "192.168.2.148",
                    "port": 80,
                    "auth": false,
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "volumeControl": 1,
                    "switchInfoMenu": false
                }
            ],
            "platform": "OpenWebIfTv"

[OpenWebIfTv] Device: 192.168.2.148 dm920, Device Info eror: Error: Request failed with status code 404
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at createError (/usr/local/lib/node_modules/homebridge-openwebif-tv/node_modules/axios/lib/core/createError.js:16:15)
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at settle (/usr/local/lib/node_modules/homebridge-openwebif-tv/node_modules/axios/lib/core/settle.js:17:12)
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-openwebif-tv/node_modules/axios/lib/adapters/http.js:260:11)
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at IncomingMessage.emit (events.js:327:22)
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at endReadableNT (internal/streams/readable.js:1327:12)
Mar 10 17:44:28 Rasp4 homebridge[25555]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by grzegorz914** [comment]
Please post Your config here

**Comment by grzegorz914** [comment]
Try this in web browser and get the output:

http://192.168.2.148/api/deviceinfo

**Comment by ekke1** [comment]
This is what I get

No Such Resource

File not found.

**Comment by ekke1** [comment]
Update:
disabled all security for the interface on the dreambox, which are actually two (token and anti-highjack).
Updated all on dreambox.
DreamMote on iPhone works well after that.
Still getting the same error in homebridge

If it helps, IP/web/about returns the following:
<e2about>
<e2enigmaversion>4.3.2r12-2020-05-12</e2enigmaversion>
<e2imageversion>Release 2017-11-07</e2imageversion>
<e2webifversion>1.9.0</e2webifversion>
<e2fpversion>None</e2fpversion>
<e2model>dm920</e2model>

**Comment by grzegorz914** [comment]
U don't get me the right antwort:

Have U openwebif installed in Your box?
Are U enabled it.?
Can U browse the web interface?
What image is installed in the box?

**Comment by grzegorz914** [comment]
I see U don't use openWebIf interface but You use old Enigma2 interface which is not compatible with this plugin.
Install openWebIf from plugins.

**Comment by ekke1** [comment]
DB is saying their Webinterface is downward compatible, but if it is not so be it.
Can’t get oenWebIf installed, since the provided GitHub-link for installation is broken.
So you can close the case.

**Comment by grzegorz914** [comment]
Enigma2 web interface is old One and use old API, uninstall this and install OpenWebIf.

**Comment by grzegorz914** [comment]
https://www.dreambox4k.com/plugin-openwebif/
