### ISSUE TITLE
3.7.50 error

### ISSUE THREAD

**Issue by wasiaks** [grzegorz914/homebridge-openwebif-tv#48]
Hi, 
after update to 3.7.50 I've got such an error:
[OpenWebIfTv] Device: 192.168.0.99 TV Living room, get device info eror: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, device offline, trying to reconnect

**Comment by grzegorz914** [comment]
Not a plugin problem, You device is not available on the network in standby mode.
