### ISSUE TITLE
New Feature if Receiver is shut off

### ISSUE THREAD

**Issue by DocUltra** [grzegorz914/homebridge-openwebif-tv#51]
Hi, is it possible to get a propertie if the set top box isn´t reachable, that will be shown as false in Homekit?

**Comment by BorussiaPlayer17** [comment]
HomeKit Shows „no answer“ when the Receiver is Not reachable?!?!

**Comment by grzegorz914** [comment]
It is correct

**Comment by DocUltra** [comment]
Yes in the dreambox plugin, there is possiblilty to overwrite this behavior with false?

**Comment by grzegorz914** [comment]
This can be done but is not correct behavior, so I close this.
