### ISSUE TITLE
Problem with recording on NAS

### ISSUE THREAD

**Issue by Bene2103** [grzegorz914/homebridge-openwebif-tv#52]
Hi, 

first of all thank you for this amazing plugin!

Last week i got a brand new VU+ Uno 4k SE so i installed VTi on the receiver and your plugin on homebridge. So far everything is working flawless.

Later i configured my network shares so i can record movies directly to my NAS (Synology). This was the point where the problems began. The receiver was stuck at loading the network share and nothing besides a reboot could help. After the reboot the same problem happens, loading bar at the top left. I've tried a few things and all of a sudden everything works fine again.

Later i tried to record a movie and the problem appeared again, so i tried disabling your plugin and everything was again working flawless. Also i can replicate this behaviour at any time.

It seems like your plugin freaks a bit out when i try to open my network shares on the VU+. Here is the Log from the plugin:

> Dec 15 18:37:57 homebridge homebridge[45022]: [12/15/2021, 6:37:57 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:37:57 homebridge homebridge[45022]: [12/15/2021, 6:37:57 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 18:37:57 homebridge homebridge[45022]: [12/15/2021, 6:37:57 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:37:57 homebridge homebridge[45022]: message repeated 39 times: [ [12/15/2021, 6:37:57 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:37:58 homebridge homebridge[45022]: [12/15/2021, 6:37:58 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:37:58 homebridge homebridge[45022]: message repeated 246 times: [ [12/15/2021, 6:37:58 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:37:59 homebridge homebridge[45022]: [12/15/2021, 6:37:59 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:37:59 homebridge homebridge[45022]: message repeated 271 times: [ [12/15/2021, 6:37:59 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:38:00 homebridge homebridge[45022]: [12/15/2021, 6:38:00 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:38:00 homebridge homebridge[45022]: message repeated 183 times: [ [12/15/2021, 6:38:00 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:38:01 homebridge homebridge[45022]: [12/15/2021, 6:38:01 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:38:01 homebridge homebridge[45022]: message repeated 260 times: [ [12/15/2021, 6:38:01 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:38:02 homebridge homebridge[45022]: [12/15/2021, 6:38:02 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:38:02 homebridge homebridge[45022]: message repeated 291 times: [ [12/15/2021, 6:38:02 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80
Dec 15 18:38:03 homebridge homebridge[45022]: message repeated 86 times: [ [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: connect ECONNREFUSED 192.168.4.187:80]
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] -------- Receiver --------
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Manufacturer: Vu+
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Model: Uno 4K SE
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Kernel: 4.1.20
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Chipset: 7252s
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Webif version: OWIF 1.2.8
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] Firmware: 15.0.0
Dec 15 18:38:03 homebridge homebridge[45022]: [12/15/2021, 6:38:03 PM] [OpenWebIfTv] ----------------------------------
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Power state successful: ON
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Channel: zdf_neo HD, Event: Die Simpsons, Reference: 1:0:19:2B7A:3F3:1:FFFF0212:0:0:0:
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Closed captions successful: 0
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Media state successful: PLAY
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Target Media state successful: PLAY
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Mute state successful: OFF
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get Volume level successful: 51
Dec 15 18:43:28 homebridge homebridge[45022]: [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get current state successful: false
Dec 15 18:43:28 homebridge homebridge[45022]: message repeated 33 times: [ [12/15/2021, 6:43:28 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, get current state successful: false]
...........
...........
...........
...........
...........
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: message repeated 9 times: [ [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded]
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 18:54:08 homebridge homebridge[45022]: [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded
Dec 15 18:54:08 homebridge homebridge[45022]: message repeated 2 times: [ [12/15/2021, 6:54:08 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded]
...........
...........
...........
...........
...........
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, update device state error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, Disconnected.
Dec 15 19:05:18 homebridge homebridge[45022]: [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded
Dec 15 19:05:18 homebridge homebridge[45022]: message repeated 2 times: [ [12/15/2021, 7:05:18 PM] [OpenWebIfTv] Device: 192.168.4.187 Receiver, device info error: Error: timeout of 5000ms exceeded]

I've left a few thousand lines out, the log is completely filled with these error messages. Also the timeout of 5000ms seems to be completely ignored.

When there are these errors in the logfile the receiver is completely unusable. Only the deactivation of your plugin helps to get the receiver working again.

It seems like the VU isnt respondig to your requests and then the receiver is DDOS'd with requests. Do you have any clue how this could happen?

The second problem i encountered is, when we go to sleep the VU turns on automatically sometime only one time during the night, sometimes two or three times. This behaviour goes away when i disable the plugin.

If you need more logs or anything please let me know!

Thank you very much!

**Comment by Bene2103** [comment]
Hi,

so yesterday i've tried it and it seems to be fixed somehow.
Did you fix it in the code already? I took a look at the last commits but it doesnt seem to have any changes related to this?

Anyway i will try further and let you know how it goes :-)

**Comment by grzegorz914** [comment]
It was code bug. On your side all was OK.
