### ISSUE TITLE
update device state timeout

### ISSUE THREAD

**Issue by BorussiaPlayer17** [grzegorz914/homebridge-openwebif-tv#53]
Hi, I keep getting a timeout while updating device state. When the receiver is disconnected HomeKit thinks it is turned off. This triggers an automation. On older versions of your plugin I did not have this issue. After a few seconds the receiver gets connected again. 

> [12/22/2021, 10:10:05 PM] [OpenWebIfTv] Device: 192.168.99.10 Receiver, update device state error: Error: timeout of 2250ms exceeded
> [12/22/2021, 10:10:05 PM] [OpenWebIfTv] Device: 192.168.99.10 Receiver, Disconnected.
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Device: 192.168.99.10 Receiver, Connected.
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] -------- Receiver --------
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Manufacturer: Vu+
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Model: Uno4K
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Kernel: 3.14.28
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Chipset: 7252s
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Webif version: OWIF 1.4.9
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] Firmware: 6.4.20211129
> [12/22/2021, 10:10:14 PM] [OpenWebIfTv] ----------------------------------

**Comment by grzegorz914** [comment]
Please update to 3.11.2 and let me know

**Comment by BorussiaPlayer17** [comment]
Hi, error still in log. But my automation is not being triggers anymore i think.

**Comment by grzegorz914** [comment]
Regardingj error  Your receiver loses  network connection  or is very busy respond to te plug-in.
