### ISSUE TITLE
Device Name, Host or Port Missing

### ISSUE THREAD

**Issue by WojtekWro** [grzegorz914/homebridge-openwebif-tv#54]
Hi, 
After last update plugin has stopped working. 
I got this message while restarting homebridge.
12/31/2021, 1:44:08 PM] [OpenWebIfTv] Device Name, Host or Port Missing

Any idea what happened?

**Comment by grzegorz914** [comment]
check your config, one of the value are missing

**Comment by WojtekWro** [comment]
This is extract from my current config. 
What can be missing? 

       {
            "devices": [
                {
                    "host": "192.168.8.25",
                    "port": 80,
                    "auth": false,
                    "disableLogInfo": false,
                    "enableDebugMode": true,
                    "switchInfoMenu": false
                }
            ],
            "platform": "OpenWebIfTv"
        },

**Comment by grzegorz914** [comment]
where is the name?

**Comment by WojtekWro** [comment]
Solved. 
Thanks.
