### ISSUE TITLE
RC App Info Button

### ISSUE THREAD

**Issue by Denzii89** [grzegorz914/homebridge-openwebif-tv#57]

**Comment by Denzii89** [comment]
Is it possible to set the Blue Button instead of the Menu Button for the RC Info Button? Im used to it to navigate through my Bouquets. Thanks for the great work btw 😊

**Comment by grzegorz914** [comment]
Done.

**Comment by Denzii89** [comment]
Thank you for the extreme fast response and implementation! Keep up the good work! Best regards 😊
