### ISSUE TITLE
Plugin doesn't Start

### ISSUE THREAD

**Issue by MasterofKungfu9999** [grzegorz914/homebridge-openwebif-tv#59]
After the latest update I get an error loading the plugin.  there is no further information although I turned on noble mode.  this is the only info:

21HOOBSFEHLERError loading plugin "homebridge-openwebif-tv"

Best regards

**Comment by grzegorz914** [comment]
Report please on HOOBS support, it is HOOBSFEHLER

**Comment by MasterofKungfu9999** [comment]
ok, i will do
