### ISSUE TITLE
bouquets configuration

### ISSUE THREAD

**Issue by pcmediapear** [grzegorz914/homebridge-openwebif-tv#6]
hello

in previous version bouquets were automatically loaded from receiver and it was not necessary to configure them
would be possible to return back this behavior?

thank you

**Comment by grzegorz914** [comment]
Yes this was before but many people have more as 97 channels in bouquets, this make the HomeKit app unresponsive(HomeKit limitation). I will check wich is the best option for this but right now I think is not a problem copy all channels to the config bouquets.

**Comment by pcmediapear** [comment]
because of this feature i have cut down my channel list to 95 ;-)
what about to load bouquets automatically only in case an additional option is configured
for example "autoBouquets": true or somethin similar

**Comment by grzegorz914** [comment]
I working on this, please be patient

**Comment by grzegorz914** [comment]
1.3.1 released witch channel read from receiver.

**Comment by pcmediapear** [comment]
i tried to test new version but it does not work...
into bouquets.json is written only "[]"

and would be possible to add option for filename?
if multiple instances are running under same user bouquets.json will be overwritten by last started instance

**Comment by grzegorz914** [comment]
Check Your Config please nad authentication option.
`{
            "accessory": "OpenWebIfTv",
            "name": "Tuner Sat",
            "host": "192.168.1.10",
            "port": 80,
            "auth": false,
            "user": "user",
            "pass": "pass",
            "speakerService": true,
            "bouquets": []
       `

**Comment by pcmediapear** [comment]
double checked and configuration is OK
are "user" and "pass" options required in case "auth" is configured to false?
i have tried lot of different configurations ;-)

**Comment by grzegorz914** [comment]
Fixed in 1.3.2

**Comment by grzegorz914** [comment]
1.3.4 added create multiinstance bouquets

**Comment by pcmediapear** [comment]
bouquet files are created but it seems they are not loaded
from log:
error: TypeError: Cannot read property 'servicereference' of undefined

**Comment by grzegorz914** [comment]
Right now only bouquets from Config bouquets are loaded. The error can ignore.

**Comment by pcmediapear** [comment]
but channel list is also empty

**Comment by pcmediapear** [comment]
after last update it works like expected, thank you!
