### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by MortRainey** [grzegorz914/homebridge-openwebif-tv#65]
Hi,

i get this Error in my Log:

"[OpenWebIfTv] Device: 10.0.0.10 Receiver, Prepare accessory error: TypeError: serviceType is not a constructor"

Last Version without this Error is 3.25.20. Device shows "no answer" in Homekit.

**Comment by grzegorz914** [comment]
Change all value `-1` in config.json to `0`

**Comment by MortRainey** [comment]
Thanks. bouquets.displayType was set to -1. Works again.
