### ISSUE TITLE
Accessory Uno4K SE experienced an address collision.

### ISSUE THREAD

**Issue by Imburdalinix** [grzegorz914/homebridge-openwebif-tv#70]
Hello,

I have been experiencing an issue with this plugin. I got lot's of errors in the Log stating, that a "address collision" had occurred. I am not sure what this means and I don't know where I should check for the issue.
In HomeKit the status is also not correct. The Device is on, but HomeKit states it is off.
Can somebody help me?

Thanks so much!

Best regards
Ivan

<img width="1384" alt="Bildschirmfoto 2024-08-21 um 18 33 09" src="https://github.com/user-attachments/assets/f5076441-c6a3-4d53-af37-8809e988ff3a">

**Comment by grzegorz914** [comment]
Try to install Homebridge 2.0 beta

**Comment by Imburdalinix** [comment]
Oh, unfortunately I'm using Hoobs... Is there nothing I can do here?

**Comment by grzegorz914** [comment]
Just report this on hoobs support

**Comment by Imburdalinix** [comment]
> Just report this on hoobs support

Hi, I have talked to Hoobs support, and while they tried their best to help me we couldn't find a solution because in the end it's up to the developers to look after the plugins.

Just asking, do you have any idea on what I could try to fix this? Maybe by installing an older version of the plugin?

**Comment by grzegorz914** [comment]
Yes, you can always install old Version, just Chose it from menu.
