### ISSUE TITLE
Devices in Homebridge available but not in iOS Home app

### ISSUE THREAD

**Issue by DenBir** [grzegorz914/homebridge-openwebif-tv#72]
Hello, I use Homebridge version 1.8.4 and this plugin in version 4.0.18. I see in the logs the configured OpenWebIf device (Vu+) and see also in the Homebridge > Device the switch button for each channel, volume or other buttons for OpenWebIf but I don't see any buttons / device in the iOS Home app.
All other plugins / devices works fine and I can control this in the iOS Home App. 
How can I add the OpenWebIf "devices" in the iOS Home app or in Automations?

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-openwebif-tv/wiki#adding-to-homekit
