### ISSUE TITLE
Missing Mac Address: false

### ISSUE THREAD

**Issue by Terminator0007** [grzegorz914/homebridge-openwebif-tv#73]
After restart of my Homebridge server and my Home Network I got this  information in log:
[10/13/2024, 1:35:41 AM] [homebridge-openwebif-tv] Device: 192.168.1.44 Octagon SF8008, Missing Mac Address: false.

Also Openwebif plugin is not active in Homekit.

BR
Jacek

**Comment by grzegorz914** [comment]
Restart network on your device, the mac adress is missing.

**Comment by Terminator0007** [comment]
> Restart network on your device, the mac adress is missing.

I did it 3 times ...

**Comment by grzegorz914** [comment]
This is bug in Enigma, some time if disconnect from network the mac adres is not assignet again.
