### ISSUE TITLE
When used in scenes device is not starting with selected input bouquet

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#9]
Hi,

While used in scenes, the device turns on and off as expected, but starting with the last used input bouquet instead of the selected one...

Best regards
birnbam

**Comment by grzegorz914** [comment]
Pllease update to the latest version 2.0.7, 
need to make changes in config and add again to the HomeKit due to moved to platform and register as external accessory.
In this case RC is always available.
